<a href="https://colab.research.google.com/github/meriemdouider1/MOIS-8-2022/blob/main/DFS%20MCC%200.66%20TEST%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import roc_auc_score, r2_score
import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
import numpy
import sklearn.metrics as metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import LeaveOneOut
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import make_scorer
import matplotlib.pyplot as plt
from sklearn.model_selection import LeaveOneOut
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn import datasets, metrics, model_selection, svm
import numpy as np
from sklearn import svm, datasets
from sklearn.metrics import auc
from sklearn.metrics import plot_roc_curve
from sklearn.model_selection import StratifiedKFold
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn import datasets, metrics, model_selection, svm
from sklearn.metrics import matthews_corrcoef
from sklearn.svm import SVC
from sklearn.metrics import cohen_kappa_score
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.feature_selection import RFE
from sklearn.pipeline import Pipeline
from matplotlib import pyplot

In [ ]:
Cl1 = '/content/cs-longia.xlsx' 
data=pd.read_excel(Cl1, sheet_name=0,header=0,index_col=False, keep_default_na=True)

In [ ]:
data

,Cs_longia,X_long,Y_lat,Bovins,Volaille,Caprins,Ovins,Equides,Coniferes,ZoneAride,...,Vent_Mars,Vent_Avril,Vent_Mai,Vent_Juin,Vent_Juill,Vent_Aout,Vent_Sept,Vent_Oct,Vent_Nov,Vent_Dec
0,1,-15.911420,23.794740,0.000000,0.000000,0.000000,0.000000,0.624435,0,97,...,6.1,6.9,7.2,7.1,7.5,7.2,6.3,5.4,5.5,4.9
1,1,-13.188370,27.132950,0.000214,0.000000,0.063449,0.034352,0.040295,0,100,...,4.8,5.6,5.7,6.4,5.9,5.9,5.7,4.3,3.7,3.8
2,1,-13.188370,27.132950,0.000214,0.000000,0.063449,0.034352,0.040295,0,100,...,4.8,5.6,5.7,6.4,5.9,5.9,5.7,4.3,3.7,3.8
3,0,-13.185620,27.157940,0.000000,0.000000,0.000000,0.000000,0.269410,0,100,...,5.1,5.6,5.5,6.2,6.2,6.2,5.7,4.1,3.7,3.9
4,0,-13.167180,27.157730,0.000000,0.000000,0.000000,0.000000,0.379107,0,100,...,5.0,5.2,5.4,5.7,6.2,5.8,5.6,4.2,3.6,3.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,1,-5.366667,35.766667,8.495770,105.550156,8.691405,15.116930,0.698221,0,0,...,4.6,4.3,4.1,3.9,3.9,4.1,4.0,4.0,4.0,4.2
250,1,-5.816667,35.783333,0.000000,0.000000,0.000000,0.000000,1.725019,0,0,...,4.6,4.1,3.8,3.7,3.7,3.7,3.3,3.6,3.8,4.0
251,1,-5.366667,35.833333,7.411978,111.459663,7.364459,15.054404,0.991284,0,0,...,4.5,4.3,4.0,4.0,3.9,4.0,3.9,4.0,3.9,4.3
252,1,-5.558611,35.841944,5.696193,5.641273,0.602672,4.306276,0.000000,0,0,...,4.6,4.0,3.8,4.1,3.7,3.4,3.6,3.6,3.4,3.6
253,1,-5.483333,35.900000,6.839514,15.082421,0.782080,6.042903,0.595441,0,0,...,4.7,4.4,3.9,3.8,3.9,3.7,4.0,4.0,4.0,4.2

In [ ]:
data["Cs_longia"]

0      1
1      1
2      1
3      0
4      0
      ..
249    1
250    1
251    1
252    1
253    1
Name: Cs_longia, Length: 254, dtype: int64

In [ ]:
X = data.loc[:, data.columns != 'Cs_longia']
y = data.Cs_longia

In [ ]:
X

,X_long,Y_lat,Bovins,Volaille,Caprins,Ovins,Equides,Coniferes,ZoneAride,ZonePel,...,Vent_Mars,Vent_Avril,Vent_Mai,Vent_Juin,Vent_Juill,Vent_Aout,Vent_Sept,Vent_Oct,Vent_Nov,Vent_Dec
0,-15.911420,23.794740,0.000000,0.000000,0.000000,0.000000,0.624435,0,97,3,...,6.1,6.9,7.2,7.1,7.5,7.2,6.3,5.4,5.5,4.9
1,-13.188370,27.132950,0.000214,0.000000,0.063449,0.034352,0.040295,0,100,0,...,4.8,5.6,5.7,6.4,5.9,5.9,5.7,4.3,3.7,3.8
2,-13.188370,27.132950,0.000214,0.000000,0.063449,0.034352,0.040295,0,100,0,...,4.8,5.6,5.7,6.4,5.9,5.9,5.7,4.3,3.7,3.8
3,-13.185620,27.157940,0.000000,0.000000,0.000000,0.000000,0.269410,0,100,0,...,5.1,5.6,5.5,6.2,6.2,6.2,5.7,4.1,3.7,3.9
4,-13.167180,27.157730,0.000000,0.000000,0.000000,0.000000,0.379107,0,100,0,...,5.0,5.2,5.4,5.7,6.2,5.8,5.6,4.2,3.6,3.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,-5.366667,35.766667,8.495770,105.550156,8.691405,15.116930,0.698221,0,0,0,...,4.6,4.3,4.1,3.9,3.9,4.1,4.0,4.0,4.0,4.2
250,-5.816667,35.783333,0.000000,0.000000,0.000000,0.000000,1.725019,0,0,0,...,4.6,4.1,3.8,3.7,3.7,3.7,3.3,3.6,3.8,4.0
251,-5.366667,35.833333,7.411978,111.459663,7.364459,15.054404,0.991284,0,0,0,...,4.5,4.3,4.0,4.0,3.9,4.0,3.9,4.0,3.9,4.3
252,-5.558611,35.841944,5.696193,5.641273,0.602672,4.306276,0.000000,0,0,58,...,4.6,4.0,3.8,4.1,3.7,3.4,3.6,3.6,3.4,3.6
253,-5.483333,35.900000,6.839514,15.082421,0.782080,6.042903,0.595441,0,0,5,...,4.7,4.4,3.9,3.8,3.9,3.7,4.0,4.0,4.0,4.2

In [ ]:
y

0      1
1      1
2      1
3      0
4      0
      ..
249    1
250    1
251    1
252    1
253    1
Name: Cs_longia, Length: 254, dtype: int64

In [ ]:
algo = GradientBoostingClassifier(n_estimators=225, learning_rate=0.1, max_features=2, max_depth=2, random_state=0,min_samples_leaf=2,subsample=1 )

# Test 0 : DFS_MCC

In [ ]:
f0= ['ZoneAride', 'VegInond', 'VarT_tri_IRM', 'Min_IRM', 'Var_IRM',
       'Moy_TempJ', 'Amp1_TempJ', 'Amp3_TempN', 'VarT_tri_TempN', 'Max_TempN',
       'VarT_ann_NDVI', 'ProfAbs_Sub', 'IR_Moy', 'Prec_Janv', 'Prec_Juill',
       'Rad_Mai', 'Tmax_Avril', 'Vent_Avril', 'Vent_Aout', 'Vent_Sept']

In [ ]:
def specificite(y_true, y_pred):
  specificite= confusion_matrix(y_true, y_pred)[0,0]/(confusion_matrix(y_true,y_pred)[0,0] + confusion_matrix(y_true, y_pred)[0,1])
  return specificite
my_scorer = make_scorer(specificite, greater_is_better=True)
def MCC(y_true, y_pred):
  MCC= matthews_corrcoef(y_true, y_pred) 
  return MCC
my_scorer1 = make_scorer(MCC, greater_is_better=True)
def présicion_positive(y_val, preds):
  cf_matrix = confusion_matrix(y_val, preds)
  pre_pos =  (cf_matrix[1,1])/(cf_matrix[1,1]+cf_matrix[0,1])
  return pre_pos
my_scorer2 = make_scorer(présicion_positive, greater_is_better=True)
def présicion_négative(y_val, preds):
  cf_matrix = confusion_matrix(y_val, preds)
  pre_pos =  (cf_matrix[0,0])/(cf_matrix[0,0]+cf_matrix[1,0])
  return pre_pos
my_scorer3 = make_scorer(présicion_négative, greater_is_better=True)
def VN(y_true, y_pred):
    value = confusion_matrix(y_true, y_pred)[0,0]
    return value
my_scorer4 = make_scorer(VN, greater_is_better=True)
def VP(y_true, y_pred):
    value = confusion_matrix(y_true, y_pred)[1,1]
    return value
my_scorer5 = make_scorer(VP, greater_is_better=True)
def FP(y_true, y_pred):
    value = confusion_matrix(y_true, y_pred)[0,1]
    return value
my_scorer6 = make_scorer(FP, greater_is_better=True)
def FN(y_true, y_pred):
    value = confusion_matrix(y_true, y_pred)[1,0]
    return value
my_scorer7 = make_scorer(FN, greater_is_better=True)

In [ ]:
cv = KFold(n_splits=5, random_state=1, shuffle=True)
# evaluate model
scores1 = cross_val_score(algo, X[f0], y, scoring='accuracy', cv=cv, n_jobs=-1)
scores2 = cross_val_score(algo, X[f0], y, scoring='recall', cv=cv, n_jobs=-1)
scores3 = cross_val_score(algo, X[f0], y, scoring=my_scorer, cv=cv, n_jobs=-1)
scores4 = cross_val_score(algo, X[f0], y, scoring=my_scorer1, cv=cv, n_jobs=-1)
scores5 = cross_val_score(algo, X[f0], y, scoring=my_scorer2, cv=cv, n_jobs=-1)
scores6 = cross_val_score(algo, X[f0], y, scoring=my_scorer3, cv=cv, n_jobs=-1)
scores7 = cross_val_score(algo, X[f0], y, scoring='roc_auc', cv=cv, n_jobs=-1)
scores8 = cross_val_score(algo, X[f0], y, scoring=my_scorer4, cv=cv, n_jobs=-1)
scores9 = cross_val_score(algo, X[f0], y, scoring=my_scorer5, cv=cv, n_jobs=-1)
scores10 = cross_val_score(algo, X[f0], y, scoring=my_scorer6, cv=cv, n_jobs=-1)
scores11 = cross_val_score(algo, X[f0], y, scoring=my_scorer7, cv=cv, n_jobs=-1)
# report performance
print('Accuracy:',scores1)
print('moy_accuracy:',mean(scores1))
print("-------------------------------------------------")
print('sensibilité :',scores2)
print('moy_sensibilité: ',mean(scores2))
print("-------------------------------------------------")
print('spécificité :',scores3)
print('moy_spécificité:',mean(scores3))
print("-------------------------------------------------")
print('MCC :',scores4)
print('MCC: ',mean(scores4))
print("-------------------------------------------------")
print('precision-po:',scores5)
print('moy_precision-po:', mean(scores5))
print("-------------------------------------------------")
print('precision-ne :',scores6)
print('moy_precision-ne:',mean(scores6))
print("-------------------------------------------------")
print('AUC :',scores7)
print('moy_AUC: ',mean(scores7))
print("-------------------------------------------------")
print('VN :',scores8)
print('VP :',scores9)
print('FP :',scores10)
print('FN :',scores11)
print("-------------------------------------------------")
print("-------------------------------------------------")

Accuracy: [0.80392157 0.82352941 0.8627451  0.78431373 0.88      ]
moy_accuracy: 0.8309019607843137
-------------------------------------------------
sensibilité : [0.74193548 0.77272727 0.8        0.8        0.875     ]
moy_sensibilité:  0.797932551319648
-------------------------------------------------
spécificité : [0.9        0.86206897 0.95238095 0.77419355 0.88461538]
moy_spécificité: 0.8746517701801352
-------------------------------------------------
MCC : [0.6269466  0.63881398 0.74071542 0.56339271 0.75961538]
MCC:  0.6658968174575681
-------------------------------------------------
precision-po: [0.92       0.80952381 0.96       0.69565217 0.875     ]
moy_precision-po: 0.8520351966873706
-------------------------------------------------
precision-ne : [0.69230769 0.83333333 0.76923077 0.85714286 0.88461538]
moy_precision-ne: 0.8073260073260073
-------------------------------------------------
AUC : [0.83790323 0.80564263 0.86666667 0.82419355 0.91185897]
moy_AUC:  0.8492530096896059
-------------------------------------------------
VN : [18 25 20 24 23]
VP : [23 17 24 16 21]
FP : [2 4 1 7 3]
FN : [8 5 6 4 3]
-------------------------------------------------
-------------------------------------------------

# DFS

In [ ]:
clmns=X.columns

In [ ]:
clmns

Index(['X_long', 'Y_lat', 'Bovins', 'Volaille', 'Caprins', 'Ovins', 'Equides',
       'Coniferes', 'ZoneAride', 'ZonePel',
       ...
       'Vent_Mars', 'Vent_Avril', 'Vent_Mai', 'Vent_Juin', 'Vent_Juill',
       'Vent_Aout', 'Vent_Sept', 'Vent_Oct', 'Vent_Nov', 'Vent_Dec'],
      dtype='object', length=225)

In [ ]:
def transform(X, fs) :
  X_ = X.copy()
  for i in range(len(fs)) :
    if fs[i] == False :
      X_.drop([clmns[i]], axis=1, inplace=True)
  return X_

In [ ]:
def Retransform (lst):
  Fs=[]      
  for i in range(225):
    if clmns[i] in lst :
       Fs.append(True)
    else :
       Fs.append(False)
  return Fs

In [ ]:
lst= ['ZoneAride', 'VegInond', 'VarT_tri_IRM', 'Min_IRM', 'Var_IRM',
       'Moy_TempJ', 'Amp1_TempJ', 'Amp3_TempN', 'VarT_tri_TempN', 'Max_TempN',
       'VarT_ann_NDVI', 'ProfAbs_Sub', 'IR_Moy', 'Prec_Janv', 'Prec_Juill',
       'Rad_Mai', 'Tmax_Avril', 'Vent_Avril', 'Vent_Aout', 'Vent_Sept']

In [ ]:
Fs = Retransform (lst)

In [ ]:
Fs

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False]

In [ ]:
cv = KFold(n_splits=5, random_state=1, shuffle=True)
explored_models = []
scores_mcc= []
models_mm=[]
def explor_mcc(fs, mcc, algo) :
  if (sum(fs) < 5 or sum(fs) > 225) :
    return
  explored_models.append(fs)
  for i in range(225) :
    neighbor = fs.copy()
    neighbor[i] = not fs[i]
    if (neighbor not in explored_models) :
      score_mcc = cross_val_score(algo, transform(X, neighbor) , y, scoring=my_scorer1, cv=cv, n_jobs=-1)
      mean_score_mcc = np.mean(score_mcc)
      explored_models.append(neighbor)
      if (mean_score_mcc >= mcc) :
        models_mm.append(neighbor)
        print("mcc", mean_score_mcc)
        print("-----------")
        scores_mcc.append(mean_score_mcc)
        explor_mcc(neighbor, mean_score_mcc, algo)

In [ ]:
transform(X,Fs)

,ZoneAride,VegInond,VarT_tri_IRM,Min_IRM,Var_IRM,Moy_TempJ,Amp1_TempJ,Amp3_TempN,VarT_tri_TempN,Max_TempN,VarT_ann_NDVI,ProfAbs_Sub,IR_Moy,Prec_Janv,Prec_Juill,Rad_Mai,Tmax_Avril,Vent_Avril,Vent_Aout,Vent_Sept
0,97,0,0,2690,0,14905,96,5,0,14561,2,4143,1.968750,2,1,24920,22.600000,6.9,7.2,6.3
1,100,0,0,3350,0,15360,312,18,1,14705,13,1828,1.375000,3,0,24082,24.600000,5.6,5.9,5.7
2,100,0,0,3350,0,15360,312,18,1,14705,13,1828,1.375000,3,0,24082,24.600000,5.6,5.9,5.7
3,100,0,0,2930,0,15264,306,21,1,14690,8,0,9.304688,3,0,24019,24.600000,5.6,6.2,5.7
4,100,0,0,2350,10,15310,295,14,0,14719,1,6537,7.515625,3,0,24002,24.700001,5.2,5.8,5.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,0,0,0,880,0,14903,543,1,0,14675,52,0,25.093750,125,1,23341,18.900000,4.3,4.1,4.0
250,0,0,0,1400,0,14838,478,4,0,14743,51,846,6.578125,113,1,23582,18.700001,4.1,3.7,3.3
251,0,0,0,1080,0,14819,452,1,0,14666,84,1729,15.914062,121,1,23425,18.900000,4.3,4.0,3.9
252,0,11,0,620,0,0,0,0,0,0,37,2786,14.812500,132,1,23716,19.799999,4.0,3.4,3.6
253,0,0,0,990,0,14703,366,3,0,14647,77,2264,30.250000,131,1,23699,19.000000,4.4,3.7,4.0

In [ ]:
explor_mcc(Fs, 0.6658968174575681, algo)

In [ ]:
len(explored_models)

226

In [ ]:
len(models_mm)

0